### ISSUE TITLE
Errors in mediapipe for Jetson Nano

### ISSUE THREAD

**Issue by jamesee** [PINTO0309/mediapipe-bin#1]
Dear  Hyodo-san,

Thank you for the wonderful repo.

I tried to install the wheel for Jetson Nano. The installation went smoothly, but when i execute the mp-hands.py sample code from google, I faced the following errors:-
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 145, in __init__
    outputs=['multi_hand_landmarks', 'multi_handedness'])
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 230, in __init__
    binary_graph_path=os.path.join(root_path, binary_graph_path))
RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: PalmDetectionCpu; Unable to find Calculator "PalmDetectionCpu"
No registered object with name: HandLandmarkCpu; Unable to find Calculator "HandLandmarkCpu"
```

The steps I did as follows. You should be able to replicate the errors:

## Hardware and Jetpack version:
<img width="1675" alt="Screenshot 2021-06-04 at 00 00 42" src="https://user-images.githubusercontent.com/37786118/120675755-f2719c80-c4c7-11eb-95e6-2262ea133aec.png">

## Installation of the wheel from your repo:
```
$ sudo apt update && \
  sudo apt install -y python3-dev protobuf-compiler python3-pip git make libssl-dev
$ sudo pip3 install pip --upgrade
$ git clone https://github.com/PINTO0309/mediapipe-bin && cd mediapipe-bin/v0.8.4/numpy119x
$ ./mediapipe-0.8-cp36-none-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh
$ sudo pip3 install *.whl
$ sudo pip3 install opencv-python
```

### filename mp-hands.py
```
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands

cap = cv2.VideoCapture(0)
with mp_hands.Hands(static_image_mode=False, max_num_hands=2, min_detection_confidence=0.5,min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # Flip the image horizontally for a later selfie-view display, and convert
    # the BGR image to RGB.
    image = cv2.cvtColor(cv2.flip(image, 1), cv2.COLOR_BGR2RGB)
    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(image, hand_landmarks, mp_hands.HAND_CONNECTIONS)
    cv2.imshow('MediaPipe Hands', image)
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()
```

## Error Messages:
```
$ python3 mp-hands.py 
Traceback (most recent call last):
  File "mp-hands.py", line 39, in <module>
    with mp_hands.Hands(static_image_mode=False, max_num_hands=2, min_detection_confidence=0.5,min_tracking_confidence=0.5) as hands:
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/hands.py", line 145, in __init__
    outputs=['multi_hand_landmarks', 'multi_handedness'])
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solution_base.py", line 230, in __init__
    binary_graph_path=os.path.join(root_path, binary_graph_path))
RuntimeError: ValidatedGraphConfig Initialization failed.
No registered object with name: PalmDetectionCpu; Unable to find Calculator "PalmDetectionCpu"
No registered object with name: HandLandmarkCpu; Unable to find Calculator "HandLandmarkCpu"
```

I would appreciate it if you could take a look at the wheel for Jetson Nano. Many thanks.

Regards,
James

**Comment by PINTO0309** [comment]
You are right. However, please see the remarks in the URL below. I just created it yesterday and it is a WIP. Currently only Pose and Holistic are supported. I'm sorry. I am very busy on weekdays, so I will work on it again when I have time on weekends. :crying_cat_face: 
https://github.com/PINTO0309/mediapipe-bin#1-binary-type

**Comment by jamesee** [comment]
Are you able to provide some guidance? Maybe I can try build the wheel...

**Comment by PINTO0309** [comment]
It's very dirty and unorganized in my work notes, so I know it's hard to understand, but I'll share it just in case. It contains many incorrect procedures.
- Try to compile mediapipe Pi4 armv7l / aarch64 etc.
https://zenn.dev/pinto0309/scraps/bb3c2089db5ef2

**Comment by jamesee** [comment]
日本語しこし分かるから「机上の空論主義者」のステップに従ってやってみます。

**Comment by jamesee** [comment]
Dear Hyodo-san

Can you explain what you mean by the code below?
Am I supposed to change the setup.py in mediapipe into something like this?

```
$ nano setup.py

    bazel_command = [
        'bazel',
        'build',
        '--compilation_mode=opt',
        '--define=MEDIAPIPE_DISABLE_GPU=1',
        '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
        os.path.join('mediapipe/modules/', graph_path),
    ]

↓

    bazel_command = [
        'bazel',
        'build',
        '--compilation_mode=opt',
        '--config=cuda',
        '--spawn_strategy=local',
        '--define=no_gcp_support=true',
        '--define=no_aws_support=true',
        '--define=no_nccl_support=true',
        '--copt=-DMESA_EGL_NO_X11_HEADERS',
        '--copt=-DEGL_NO_X11',
        '--local_ram_resources=4096',
        '--local_cpu_resources=3',
        '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
        os.path.join('mediapipe/modules/', graph_path),
    ]

===================================================

    bazel_command = [
        'bazel',
        'build',
        '--compilation_mode=opt',
        '--define=MEDIAPIPE_DISABLE_GPU=1',
        '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
        str(ext.bazel_target + '.so'),
    ]

↓

    bazel_command = [
        'bazel',
        'build',
        '--compilation_mode=opt',
        '--config=cuda',
        '--spawn_strategy=local',
        '--define=no_gcp_support=true',
        '--define=no_aws_support=true',
        '--define=no_nccl_support=true',
        '--copt=-DMESA_EGL_NO_X11_HEADERS',
        '--copt=-DEGL_NO_X11',
        '--local_ram_resources=4096',
        '--local_cpu_resources=3',
        '--action_env=PYTHON_BIN_PATH=' + _normalize_path(sys.executable),
        str(ext.bazel_target + '.so'),
    ]
```

**Comment by jamesee** [comment]
> 日本語しこし分かるから「机上の空論主義者」のステップに従ってやってみます。

When I followed the article 「机上の空論主義者」, I had the segmentation dump.

```
$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe as mp
Segmentation fault (core dumped)
```

**Comment by PINTO0309** [comment]
> Am I supposed to change the setup.py in mediapipe into something like this?

Yes. As stated, two places need to be corrected. This fix is necessary to make Jetson's GPU aware.

> When I followed the article 「机上の空論主義者」, I had the "segmentation fault (core dump)".

The procedure in this article is incorrect.

From here.
https://zenn.dev/pinto0309/scraps/bb3c2089db5ef2#comment-a3a621d261d8ba
Up to this point, the procedure works correctly.
https://zenn.dev/pinto0309/scraps/bb3c2089db5ef2#comment-9703e17342c248

The articles pasted in several places along the way are almost useless and should be ignored.

Also, the note about Hand_Detection from here on down is completely wrong, so if you work as described, a Segmentation Fault will occur. 
https://zenn.dev/pinto0309/scraps/bb3c2089db5ef2#comment-9703e17342c248

If the .pbtxt is modified in the wrong way (linking between modules) and built incorrectly, MediaPipe will output a clear error message or Segmentation Fault.

**Comment by PINTO0309** [comment]
@jamesee 
I was able to get Hand Pose to work. I'm trying other models as well.

![ezgif com-gif-maker (13)](https://user-images.githubusercontent.com/33194443/120892553-e7467a00-c649-11eb-825f-ad3ea083671e.gif)

**Comment by PINTO0309** [comment]
Selfie Segmentation
![ezgif com-gif-maker (14)](https://user-images.githubusercontent.com/33194443/120896007-82dfe680-c65a-11eb-9c57-aaf28e40a659.gif)

**Comment by PINTO0309** [comment]
Added support for
1. Pose
2. Holistic
3. Selfie Segmentation
4. Multi Hand Tracking

- v0.8.5
**https://github.com/PINTO0309/mediapipe-bin/tree/main/v0.8.5/numpy119x**

**Comment by jamesee** [comment]
> Added support for
> 
> 1. Pose
> 2. Holistic
> 3. Selfie Segmentation
> 4. Multi Hand Tracking
> 
> * v0.8.5
>   **https://github.com/PINTO0309/mediapipe-bin/tree/main/v0.8.5/numpy119x**
> * [WIP] Here's a step-by-step article that I'm organizing and rewriting.
>   **[Verification of mediapipe's GPU-enabled .pbtxt processing method](https://zenn.dev/pinto0309/scraps/71368ef3d74438)**


Impressive. Many thanks.

**Comment by jamesee** [comment]
Dear Hyodo-san

I don't know whether is it me or what, I just could not get it working.
I flashed a new Jetpack4.5 sd card, and followed your installation instruction, but the same error kept coming up. I cut-and-pasted the steps below. Please assist to see where I when wrong ...

```
james@jetson-nano:~/mediapipe-bin$ ./v0.8.5/numpy119x/mediapipe-0.8.5_cuda102-cp36-cp36m-linux_aarch64_numpy119x_jetsonnano_L4T32.5.1_download.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0    100      0 --:--:--  0:00:04 --:--:--   100
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
100 11.6M    0 11.6M    0     0  2124k      0 --:--:--  0:00:05 --:--:-- 20.7M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0    239      0 --:--:--  0:00:01 --:--:--   239
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100 19.6M    0 19.6M    0     0  5961k      0 --:--:--  0:00:03 --:--:-- 28.9M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   408    0   408    0     0   1378      0 --:--:-- --:--:-- --:--:--  1378
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 36.9M    0 36.9M    0     0  15.2M      0 --:--:--  0:00:02 --:--:-- 32.4M
Download finished.
james@jetson-nano:~/mediapipe-bin$ ls
LICENSE                                              opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl  v0.8.5
mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl  README.md
numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl     v0.8.4
james@jetson-nano:~/mediapipe-bin$ sudo pip3 install \
> numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl \
> opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl \
> mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl
WARNING: The directory '/home/james/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing ./numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl
Processing ./opencv_contrib_python-4.5.2.52-cp36-none-linux_aarch64.whl
Processing ./mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from mediapipe==0.8.5-cuda102) (1.11.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.6/dist-packages (from mediapipe==0.8.5-cuda102) (0.36.2)
Collecting protobuf>=3.11.4
  Downloading protobuf-3.17.2-py2.py3-none-any.whl (173 kB)
     |████████████████████████████████| 173 kB 8.5 MB/s 
Collecting absl-py
  Downloading absl_py-0.12.0-py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 13.9 MB/s 
Collecting attrs>=19.1.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 14.2 MB/s 
Installing collected packages: numpy, protobuf, opencv-contrib-python, attrs, absl-py, mediapipe
  Attempting uninstall: numpy
    Found existing installation: numpy 1.13.3
    Uninstalling numpy-1.13.3:
      Successfully uninstalled numpy-1.13.3
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.0.0
    Uninstalling protobuf-3.0.0:
      Successfully uninstalled protobuf-3.0.0
Successfully installed absl-py-0.12.0 attrs-21.2.0 mediapipe-0.8.5-cuda102 numpy-1.19.4 opencv-contrib-python-4.5.2.52 protobuf-3.17.2
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
james@jetson-nano:~/mediapipe-bin$ sudo pip3 install opencv-python
WARNING: The directory '/home/james/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting opencv-python
  Downloading opencv_python-4.5.1.48-cp36-cp36m-manylinux2014_aarch64.whl (34.5 MB)
     |████████████████████████████████| 34.5 MB 31.2 MB/s 
Requirement already satisfied: numpy>=1.19.3 in /usr/local/lib/python3.6/dist-packages (from opencv-python) (1.19.4)
Installing collected packages: opencv-python
Successfully installed opencv-python-4.5.1.48
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
james@jetson-nano:~/mediapipe-bin$ cd
james@jetson-nano:~$ cd mediapipe-python-sample/
james@jetson-nano:~/mediapipe-python-sample$ ls
image    old        sample_facedetection.py  sample_hand.py      sample_objectron.py  sample_selfie_segmentation.py
LICENSE  README.md  sample_facemesh.py       sample_holistic.py  sample_pose.py       utils
james@jetson-nano:~/mediapipe-python-sample$ export DISPLAY=:0
james@jetson-nano:~/mediapipe-python-sample$ xhost +
access control disabled, clients can connect from any host
james@jetson-nano:~/mediapipe-python-sample$ python3 sample_hand.py 
Traceback (most recent call last):
  File "sample_hand.py", line 8, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_utils
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/drawing_utils.py", line 21, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by jamesee** [comment]
Seems like I cannot even import mediapipe.

```
james@jetson-nano:~/mediapipe-bin$ python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mediapipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_utils
  File "/usr/local/lib/python3.6/dist-packages/mediapipe/python/solutions/drawing_utils.py", line 21, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
>>> 

```

**Comment by PINTO0309** [comment]
All you have to do is look up "dataclasses" in a Google search.
https://pypi.org/project/dataclasses/

**Comment by jamesee** [comment]
Thanks. Managed to get it working.

However, I noticed that the program complained that it can't find  "mediapipe/modules/palm_detection/palm_detection.tflite" and " mediapipe/modules/hand_landmark/hand_landmark.tflite"
```
james@jetson-nano:~/mediapipe-python-sample$ python3 sample_hand.py 
[libprotobuf WARNING external/com_google_protobuf/src/google/protobuf/text_format.cc:324] Warning parsing text-format mediapipe.CalculatorGraphConfig: 125:5: text format contains deprecated field "use_gpu"
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20210606 15:26:21.539467 13749 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210606 15:26:21.579632 13759 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 32.5.1)
I20210606 15:26:21.579938 13749 gl_context_egl.cc:163] Successfully initialized EGL. Major : 1 Minor: 5
I20210606 15:26:21.597982 13760 gl_context.cc:331] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 32.5.1)
W20210606 15:26:21.602038 13759 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/palm_detection/palm_detection.tflite
INFO: Created TensorFlow Lite delegate for GPU.
W20210606 15:26:31.440555 13759 tflite_model_loader.cc:32] Trying to resolve path manually as GetResourceContents failed: ; Can't find file: mediapipe/modules/hand_landmark/hand_landmark.tflite

```

**Comment by PINTO0309** [comment]
You can ignore that warning message and it will work fine.

**Comment by jamesee** [comment]
Noted with thanks.
