### ISSUE TITLE
mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl for Jetson-nano not working again ...

### ISSUE THREAD

**Issue by jamesee** [PINTO0309/mediapipe-bin#4]
Dear Hyodo-san,

Sorry to bother you again.
Few days ago, I managed to get the jetson-nano working. Have been playing with it for the last few days.

Today, when I re-install the wheel again with a new SD card, I got the following errors:
```
james@jetson-nano:~/mediapipe-bin/v0.8.5/numpy119x$ sudo pip3 install mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl 
WARNING: The directory '/home/james/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing ./mediapipe-0.8.5_cuda102-cp36-none-linux_aarch64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 204, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 319, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 104, in resolve
    req, requested_extras=()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 434, in make_requirement_from_install_req
    version=None,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 205, in _make_candidate_from_link
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in __init__
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 151, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 234, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in _prepare_distribution
    self._ireq, parallel_builds=True
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 508, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 571, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 61, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/wheel.py", line 27, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by jamesee** [comment]
I redo a new SD card, and reinstalled your wheel. It worked. 

Seems like my previous SD card was corrupted.

Sorry for the false report.
